### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ziracul** [G-On-dev/homebridge-g-on-alice#2]
[2019-7-17 21:33:00] [G-On Alice] Action on 192.168.1.85 51826 undefined Error: Homebridge auth failed, invalid PIN undefined
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/hap-node-client/HAPNodeJSClient.js:200:18)
    at Request._callback (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)

**Comment by denis86111** [comment]
У меня все работает. Просто нужно добавить строчку с пином в конфиг бриджа. 
Другой вопрос, создатели плагина отвечают когда нибудь?
У меня добавился только один акара выключатель, остальные нет и почему плагин не проверяет состояние устройств в хоумбридж?

**Comment by Ziracul** [comment]
с чем добавить строчку?

**Comment by denis86111** [comment]
Нужно добавить строчку в конфиг
 "pin": "031-45-155"
Пин сменить на пин твоего homebridge

**Comment by Ziracul** [comment]
решено 
спасибо
