### ISSUE TITLE
Не работает на Homebridge v 1.0.0.

### ISSUE THREAD

**Issue by sergoo-lbt** [G-On-dev/homebridge-g-on-alice#9]
![BC525F5F-A46F-48D5-90F7-7A8CBE7C6F7D](https://user-images.githubusercontent.com/64399012/80342723-15ba2900-887e-11ea-92fd-a6718ce30268.png)

**Comment by DedMsk** [comment]
Тоже пришлось возвращать бридж на предыдущую версию

**Comment by stalkerj** [comment]
+1

**Comment by bdya** [comment]
Та же история

[4/28/2020, 19:21:12] TypeError: Cannot read property 'Name' of undefined
    at Accessory.getDeviceCapabilities (/usr/lib/node_modules/homebridge-g-on-alice/lib/parse/Accessory.js:35:21)
    at Homebridge.getDevicesAndCapabilities (/usr/lib/node_modules/homebridge-g-on-alice/lib/parse/Homebridge.js:35:36)
    at Homebridges.getDevicesAndCapabilities (/usr/lib/node_modules/homebridge-g-on-alice/lib/parse/Homebridges.js:29:35)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-g-on-alice/lib/aliceActions.js:30:26)
    at HAPNodeJSClient.HAPaccessories (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/hap-node-client/HAPNodeJSClient.js:163:3)
    at Object.aliceDiscovery (/usr/lib/node_modules/homebridge-g-on-alice/lib/aliceActions.js:26:14)
    at HAPNodeJSClient.<anonymous> (/usr/lib/node_modules/homebridge-g-on-alice/lib/aliceActions.js:18:20)
    at HAPNodeJSClient.emit (events.js:310:20)
    at HAPNodeJSClient._discoveryEnd (/usr/lib/node_modules/homebridge-g-on-alice/node_modules/hap-node-client/HAPNodeJSClient.js:149:8)
    at listOnTimeout (internal/timers.js:549:17)

**Comment by meowlab-net** [comment]
В 1.0.3  тоже не работает.

**Comment by SSFix** [comment]
1.0.4 не работает((

**Comment by Supereg** [comment]
@G-On-dev some of the protocol used by HAP-NodeJS changed to adhere more to the HomeKit specifications. As far as I seem to understand this plugin only really needs an update of the dependency `hap-node-client`.

**Comment by Supereg** [comment]
The issue is caused by the transition to short uuids on all HAP-NodeJS responses (as defined in 6.6.1 of HAP spec R2 non-commercial).

This was supported with https://github.com/NorthernMan54/Hap-Node-Client/commit/539c23f98fd99eba06fc52d0439790b73642a31a

**Comment by oznu** [comment]
@sergoo-lbt 

This may temporarily fix the issue until @G-On-dev has a chance to update.

```
cd /usr/lib/node_modules/homebridge-g-on-alice
sudo npm install hap-node-client@latest
```

Beaware there may be some other breaking changes in the hap-node-client between the current version required,  [0.0.25](https://github.com/G-On-dev/homebridge-g-on-alice/blob/master/package.json#L30) and the latest version which is `0.1.2`.

**Comment by bdya** [comment]
@oznu 
Спасибо за идею. К сожалению, решение не работает. Homebridge перестает падать, но плагин перестает взаимодействовать с устройствами.

**Comment by meowlab-net** [comment]
@bdya
У меня заработало, но пришлось переспарить учетки.

**Comment by sergoo-lbt** [comment]
> @bdya
> У меня заработало, но пришлось переспарить учетки, удалить все устройства и настроить заново.
> 
> @oznu
> Thanks. Its worked.
Не поможете с этим?
![AA03FAB0-1FA0-4E9F-84B8-405195CF5FBD](https://user-images.githubusercontent.com/64399012/80869321-3b4d9500-8cb9-11ea-977f-ce0e31023134.jpeg)

**Comment by Supereg** [comment]
@sergoo-lbt You will need to find out where node installs you global packages. This can be different on certain machines.

Try the following. Run the following command 

```
npm list -g homebridge-g-on-alice --depth=0
```

This will produce an output like 
```
/usr/lib
└── homebridge-g-on-alice@0.1.4
```

`/usr/lib` is in this case the base directory. This part is probably different for you.

Now you can navigate into the plugin directory
```
cd /usr/lib/node_modules/homebridge-g-on-alice
```

**Comment by sergoo-lbt** [comment]
> @sergoo-lbt You will need to find out where node installs you global packages. This can be different on certain machines.
> 
> Try the following. Run the following command
> 
> ```
> npm list -g homebridge-g-on-alice --depth=0
> ```
> 
> This will produce an output like
> 
> ```
> /usr/lib
> └── homebridge-g-on-alice@0.1.4
> ```
> 
> `/usr/lib` is in this case the base directory. This part is probably different for you.
> 
> Now you can navigate into the plugin directory
> 
> ```
> cd /usr/lib/node_modules/homebridge-g-on-alice
> ```

Low bow to you! Everything worked out!

**Comment by bdya** [comment]
@meowlab-net 

Пробовал перепривязать аккаунт тоже. В homebridge пытается отдать устройства.

![Снимок экрана 2020-05-02 в 19 56 31](https://user-images.githubusercontent.com/32038907/80870465-456a9600-8caf-11ea-8e86-9312b2fbedd3.png)

Яндекс приложение ошибку рисует и не обновляет устройства. 

![Снимок экрана 2020-05-02 в 19 58 52](https://user-images.githubusercontent.com/32038907/80870493-6e8b2680-8caf-11ea-8a42-05884d950a2d.png)

**Comment by meowlab-net** [comment]
@bdya 
В Яндексе в плагине  G-On  отвязал аккаунт, устройства удалились. Перезагрузил homebridge. Привязал аккаунт к плагину в Яндексе, появились устройства. Раскидал по комнатам и переименовал. Работает.

**Comment by stepanovalex** [comment]
Та же проблема. Система крутится на Ubuntu 19.10. Все обновлено до актуальных версий (homebridge 1.0.4, homebridge-g-on-alice v0.1.5)

В логе Homebridge:
![photo_2020-05-05 12 35 03](https://user-images.githubusercontent.com/5058057/81052849-de2a2d00-8ecc-11ea-8575-bad666ee87e5.jpeg)

А в приложении - ошибка.
<img width="674" alt="Снимок экрана 2020-05-05 в 12 33 29" src="https://user-images.githubusercontent.com/5058057/81052757-b3d86f80-8ecc-11ea-94c3-5b66b589b200.png">

Все перегружал (неоднократно), аккаунт - отвязывал/привязывал. Не помогает.

**Comment by andreyxc** [comment]
У меня свой сервер , та-же ошибка , что у Яндекса .

**Comment by SSFix** [comment]
у меня заработал после того как прописал pin бриджа в конфиге. homebridge 1.0.4

**Comment by DedMsk** [comment]
> у меня заработал после того как прописал pin бриджа в конфиге. homebridge 1.0.4
> "platforms": [
> {
> "platform": "G-On Alice",
> "name": "G-On Alice",
> "username": "....",
> "password": "....",
> "pin": "xxx-xx-xxx"
> }
> ],

Не помогло

**Comment by sergoo-lbt** [comment]
@DedMsk , а бридж стартует на 1.0.4 с Алисой? Или падает?

**Comment by stepanovalex** [comment]
Бридж стартует и стабильно работает. Без прописанного пин-кода первоначально оборудование появлялось в Яндексе, но не управлялось. Сейчас не добавляется (пин-код прописан).

**Comment by bdya** [comment]
Удалось мне победить Алису. В поисках конфликта нашел, что плагин "Camera-ffmpeg" мешал обновить устройства в Яндексе. Удалил в конфиге  "platform": "Camera-ffmpeg", обновил устройства в Яндексе, вернул плагин в конфиге. Все работает. Стоит офф бридж последней версии с плагином последней версии и обновленным hap-node-client в плагине g-on.

**Comment by stepanovalex** [comment]
Подтверждаю. Те же манипуляции (удалить в конфиге ffmpeg, ребут хомбриджа, обновление (добавление) устройств в яндексе, возвращение конфига на место, ребут хомбриджа) - все заработало.
